{
  "mcpServers":
    {
      "mcp-server-snowflake":
        {
          "command": "uvx",
          "args":
            [
              "snowflake-labs-mcp",
              "--service-config-file",
              "C:/Users/alejandro.pedrero/cortex-code-hands-on/tools_config.yaml",
              "--connection-name",
              "default",
            ],
          "env": { "SNOWFLAKE_PASSWORD": "${SNOWFLAKE_PASSWORD}" },
        },
    },
}
