-- Monthly Revenue Summary for Pinnacle Financial
-- Source: PINNACLE_FINANCIAL.ANALYTICS.FACT_REVENUE
-- Period: Jul 2025 - Jan 2026

-- 1. Monthly Revenue Overview
SELECT
    TO_DATE(MIN(DATE_KEY)::VARCHAR, 'YYYYMMDD') AS MONTH_DATE,
    TO_CHAR(TO_DATE(MIN(DATE_KEY)::VARCHAR, 'YYYYMMDD'), 'Mon YYYY') AS MONTH_LABEL,
    COUNT(*) AS TRANSACTION_COUNT,
    ROUND(SUM(REVENUE_AMOUNT), 2) AS TOTAL_REVENUE,
    ROUND(AVG(REVENUE_AMOUNT), 2) AS AVG_REVENUE_PER_TXN,
    ROUND(SUM(AUM_AT_BILLING), 2) AS TOTAL_AUM_AT_BILLING
FROM PINNACLE_FINANCIAL.ANALYTICS.FACT_REVENUE
GROUP BY FLOOR(DATE_KEY / 100)
ORDER BY MONTH_DATE;

-- 2. Total Revenue Across All Months
SELECT
    ROUND(SUM(REVENUE_AMOUNT), 2) AS TOTAL_REVENUE_ALL_MONTHS
FROM PINNACLE_FINANCIAL.ANALYTICS.FACT_REVENUE;

-- 3. Peak and Lowest Revenue Months
SELECT
    TO_CHAR(TO_DATE(MIN(DATE_KEY)::VARCHAR, 'YYYYMMDD'), 'Mon YYYY') AS MONTH_LABEL,
    ROUND(SUM(REVENUE_AMOUNT), 2) AS TOTAL_REVENUE
FROM PINNACLE_FINANCIAL.ANALYTICS.FACT_REVENUE
GROUP BY FLOOR(DATE_KEY / 100)
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

SELECT
    TO_CHAR(TO_DATE(MIN(DATE_KEY)::VARCHAR, 'YYYYMMDD'), 'Mon YYYY') AS MONTH_LABEL,
    ROUND(SUM(REVENUE_AMOUNT), 2) AS TOTAL_REVENUE
FROM PINNACLE_FINANCIAL.ANALYTICS.FACT_REVENUE
GROUP BY FLOOR(DATE_KEY / 100)
ORDER BY TOTAL_REVENUE ASC
LIMIT 1;

-- 4. Month-over-Month Revenue Change
WITH monthly AS (
    SELECT
        FLOOR(DATE_KEY / 100) AS YEAR_MONTH,
        TO_CHAR(TO_DATE(MIN(DATE_KEY)::VARCHAR, 'YYYYMMDD'), 'Mon YYYY') AS MONTH_LABEL,
        ROUND(SUM(REVENUE_AMOUNT), 2) AS TOTAL_REVENUE
    FROM PINNACLE_FINANCIAL.ANALYTICS.FACT_REVENUE
    GROUP BY FLOOR(DATE_KEY / 100)
)
SELECT
    MONTH_LABEL,
    TOTAL_REVENUE,
    LAG(TOTAL_REVENUE) OVER (ORDER BY YEAR_MONTH) AS PREV_MONTH_REVENUE,
    ROUND(TOTAL_REVENUE - LAG(TOTAL_REVENUE) OVER (ORDER BY YEAR_MONTH), 2) AS MOM_CHANGE,
    ROUND((TOTAL_REVENUE - LAG(TOTAL_REVENUE) OVER (ORDER BY YEAR_MONTH))
        / LAG(TOTAL_REVENUE) OVER (ORDER BY YEAR_MONTH) * 100, 2) AS MOM_CHANGE_PCT
FROM monthly
ORDER BY YEAR_MONTH;
