-- Pinnacle Financial Services - Financial Analytics POC Schema
-- Designed for: Revenue analytics, Expense tracking, Client profitability

CREATE SCHEMA IF NOT EXISTS PINNACLE_FINANCIAL_DEMO_33.FINANCE_ANALYTICS;
USE SCHEMA PINNACLE_FINANCIAL_DEMO_33.FINANCE_ANALYTICS;

-- ============================================
-- DIMENSION TABLES
-- ============================================

CREATE OR REPLACE TABLE DIM_CLIENT (
    CLIENT_KEY INT PRIMARY KEY,
    CLIENT_ID VARCHAR(20) NOT NULL,
    CLIENT_NAME VARCHAR(200) NOT NULL,
    CLIENT_SEGMENT VARCHAR(50) NOT NULL,  -- Individual, Institutional, Family Office
    RELATIONSHIP_START_DATE DATE,
    RELATIONSHIP_MANAGER VARCHAR(100),
    OFFICE_LOCATION VARCHAR(50),          -- New York, Boston, San Francisco
    AUM_TIER VARCHAR(20),                 -- Platinum, Gold, Silver
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_KEY INT PRIMARY KEY,
    PRODUCT_ID VARCHAR(20) NOT NULL,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    PRODUCT_CATEGORY VARCHAR(50) NOT NULL, -- Management Fee, Performance Fee, Advisory Fee, Transaction Fee
    FEE_TYPE VARCHAR(30),                  -- Basis Points, Flat Fee, Percentage
    ASSET_CLASS VARCHAR(50),               -- Equity, Fixed Income, Alternatives, Multi-Asset
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY INT PRIMARY KEY,
    CALENDAR_DATE DATE NOT NULL,
    DAY_OF_WEEK INT,
    DAY_NAME VARCHAR(10),
    DAY_OF_MONTH INT,
    DAY_OF_YEAR INT,
    WEEK_OF_YEAR INT,
    MONTH_NUMBER INT,
    MONTH_NAME VARCHAR(10),
    QUARTER_NUMBER INT,
    QUARTER_NAME VARCHAR(6),              -- Q1, Q2, Q3, Q4
    YEAR_NUMBER INT,
    FISCAL_QUARTER INT,
    FISCAL_YEAR INT,
    IS_MONTH_END BOOLEAN,
    IS_QUARTER_END BOOLEAN,
    IS_YEAR_END BOOLEAN,
    IS_BUSINESS_DAY BOOLEAN
);

CREATE OR REPLACE TABLE DIM_COST_CENTER (
    COST_CENTER_KEY INT PRIMARY KEY,
    COST_CENTER_ID VARCHAR(20) NOT NULL,
    COST_CENTER_NAME VARCHAR(100) NOT NULL,
    EXPENSE_CATEGORY VARCHAR(50) NOT NULL, -- Compensation, Technology, Professional Services, Occupancy, Marketing
    DEPARTMENT VARCHAR(50),
    OFFICE_LOCATION VARCHAR(50),
    MANAGER VARCHAR(100),
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE DIM_GL_ACCOUNT (
    GL_ACCOUNT_KEY INT PRIMARY KEY,
    GL_ACCOUNT_ID VARCHAR(20) NOT NULL,
    GL_ACCOUNT_NAME VARCHAR(100) NOT NULL,
    ACCOUNT_TYPE VARCHAR(30) NOT NULL,     -- Revenue, Expense, Asset, Liability
    ACCOUNT_SUBTYPE VARCHAR(50),
    NORMAL_BALANCE VARCHAR(10),            -- Debit, Credit
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

-- ============================================
-- FACT TABLES
-- ============================================

CREATE OR REPLACE TABLE FACT_REVENUE (
    REVENUE_KEY INT AUTOINCREMENT PRIMARY KEY,
    DATE_KEY INT NOT NULL REFERENCES DIM_DATE(DATE_KEY),
    CLIENT_KEY INT NOT NULL REFERENCES DIM_CLIENT(CLIENT_KEY),
    PRODUCT_KEY INT NOT NULL REFERENCES DIM_PRODUCT(PRODUCT_KEY),
    GL_ACCOUNT_KEY INT NOT NULL REFERENCES DIM_GL_ACCOUNT(GL_ACCOUNT_KEY),
    TRANSACTION_ID VARCHAR(50),
    AUM_AMOUNT DECIMAL(18,2),              -- Assets under management at time of fee
    REVENUE_AMOUNT DECIMAL(18,2) NOT NULL, -- Actual fee revenue
    FEE_BASIS_POINTS DECIMAL(8,4),         -- Fee rate in basis points
    TRANSACTION_COUNT INT DEFAULT 1,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE FACT_EXPENSE (
    EXPENSE_KEY INT AUTOINCREMENT PRIMARY KEY,
    DATE_KEY INT NOT NULL REFERENCES DIM_DATE(DATE_KEY),
    COST_CENTER_KEY INT NOT NULL REFERENCES DIM_COST_CENTER(COST_CENTER_KEY),
    GL_ACCOUNT_KEY INT NOT NULL REFERENCES DIM_GL_ACCOUNT(GL_ACCOUNT_KEY),
    TRANSACTION_ID VARCHAR(50),
    EXPENSE_AMOUNT DECIMAL(18,2) NOT NULL,
    VENDOR_NAME VARCHAR(200),
    DESCRIPTION VARCHAR(500),
    PAYMENT_STATUS VARCHAR(20),            -- Pending, Paid, Accrued
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE FACT_BUDGET (
    BUDGET_KEY INT AUTOINCREMENT PRIMARY KEY,
    DATE_KEY INT NOT NULL REFERENCES DIM_DATE(DATE_KEY),
    COST_CENTER_KEY INT REFERENCES DIM_COST_CENTER(COST_CENTER_KEY),
    GL_ACCOUNT_KEY INT NOT NULL REFERENCES DIM_GL_ACCOUNT(GL_ACCOUNT_KEY),
    PRODUCT_KEY INT REFERENCES DIM_PRODUCT(PRODUCT_KEY),
    BUDGET_TYPE VARCHAR(20) NOT NULL,      -- Revenue, Expense
    BUDGET_AMOUNT DECIMAL(18,2) NOT NULL,
    BUDGET_VERSION VARCHAR(20),            -- Original, Revised, Forecast
    FISCAL_YEAR INT NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE FACT_CLIENT_AUM (
    AUM_KEY INT AUTOINCREMENT PRIMARY KEY,
    DATE_KEY INT NOT NULL REFERENCES DIM_DATE(DATE_KEY),
    CLIENT_KEY INT NOT NULL REFERENCES DIM_CLIENT(CLIENT_KEY),
    PRODUCT_KEY INT NOT NULL REFERENCES DIM_PRODUCT(PRODUCT_KEY),
    AUM_AMOUNT DECIMAL(18,2) NOT NULL,
    AUM_CHANGE DECIMAL(18,2),              -- Change from prior period
    NET_FLOWS DECIMAL(18,2),               -- Client deposits/withdrawals
    MARKET_CHANGE DECIMAL(18,2),           -- Market appreciation/depreciation
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
